# Generated by Django 5.0.1 on 2024-02-08 19:21

import django.db.models.deletion
import services.uploader
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='adi')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='ad')),
                ('surname', models.CharField(max_length=255, verbose_name='soyad')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                ('phone', models.CharField(max_length=255, verbose_name='telefon')),
                ('adress1', models.CharField(max_length=255, verbose_name='adress 1')),
                ('adress2', models.CharField(max_length=255, verbose_name='adress 2')),
                ('country', models.CharField(choices=[('usa', 'Amerika'), ('az', 'Azerbaijan'), ('eu', 'Europa'), ('as', 'Asia')], max_length=255, verbose_name='olke adlari')),
                ('city', models.CharField(max_length=255, verbose_name='sheher adi')),
                ('state', models.CharField(max_length=255, verbose_name='dovlet')),
                ('zipcode', models.CharField(max_length=255, verbose_name='olke kodu')),
            ],
            options={
                'verbose_name': 'checkout',
                'verbose_name_plural': 'checkout',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name', models.TextField(verbose_name='mehsulun rengi')),
            ],
            options={
                'verbose_name': 'reng',
                'verbose_name_plural': 'rengler',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='ad ve soyad')),
                ('email', models.CharField(max_length=255, verbose_name='email adress')),
                ('subject', models.CharField(max_length=255, verbose_name='movzu')),
                ('mesage', models.TextField(verbose_name='mesaj')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contactlar',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MainDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('adresss', models.CharField(max_length=255, verbose_name='adress')),
                ('phones', models.CharField(max_length=255, verbose_name='phones')),
                ('locations', models.TextField(blank=True, null=True, verbose_name='locations')),
            ],
            options={
                'verbose_name': 'elaqe melumati',
                'verbose_name_plural': 'elaqe melumatlari',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Partniors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.upload_photo_partniors)),
            ],
            options={
                'verbose_name': 'partnior sekil',
                'verbose_name_plural': 'partnior sekiller',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=255, verbose_name='email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name', models.TextField(verbose_name='mehsulun olcusu')),
            ],
            options={
                'verbose_name': 'olcu',
                'verbose_name_plural': 'olculer',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.upload_photo_slider)),
                ('title', models.CharField(max_length=255, verbose_name='basliq')),
                ('text', models.TextField(verbose_name='metn')),
            ],
            options={
                'verbose_name': 'slider',
                'verbose_name_plural': 'sliders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SosialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sosial_name', models.CharField(choices=[('insta', 'Instagram'), ('fb', 'Facebook'), ('wp', 'WhatsApp'), ('twitter', 'Twitter'), ('linkedin', 'Linkedin'), ('tiktok', 'Tiktok')], max_length=255, verbose_name='sosial media hesabi')),
                ('sosial_link', models.TextField(verbose_name='sosial media linki')),
            ],
            options={
                'verbose_name': 'sosial media hesabi',
                'verbose_name_plural': 'sosial media hesablari',
                'ordering': ('sosial_name',),
            },
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('text', models.TextField(verbose_name='metn')),
                ('discount', models.TextField(verbose_name='endirim')),
                ('image', models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.upload_photo_special_offer)),
            ],
            options={
                'verbose_name': 'xususi teklif',
                'verbose_name_plural': 'xususi teklifler',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='mehsulun adi')),
                ('price', models.FloatField(verbose_name='mehsulun qiymeti')),
                ('description_L', models.TextField(verbose_name='kicik movzu')),
                ('description_B', models.TextField(verbose_name='boyuk movzu')),
                ('rating', models.FloatField(verbose_name='reyting')),
                ('information', models.TextField(verbose_name='mehsul haqqinda')),
                ('is_seen', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.category')),
                ('color', models.ManyToManyField(to='my_app.color', verbose_name='reng')),
                ('size', models.ManyToManyField(to='my_app.size', verbose_name='olcu')),
            ],
            options={
                'verbose_name': 'mehsul',
                'verbose_name_plural': 'mehsullar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name="User's comment")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.product')),
            ],
            options={
                'verbose_name': 'Rey',
                'verbose_name_plural': 'Reyler',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('count', models.IntegerField()),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.product')),
            ],
            options={
                'verbose_name': 'sebet',
                'verbose_name_plural': 'sebetler',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.product')),
            ],
            options={
                'verbose_name': 'mehsul shekili',
                'verbose_name_plural': 'mehsul shekilleri',
                'ordering': ('-created_at',),
            },
        ),
    ]
